# This is a config for E2B sandbox template.
# You can use template ID (bj6xgzx26nbp86pbdia6) or template name (vibe-nextjs-prod) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-nextjs-prod") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-prod") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-prod')

team_id = "5e7bad97-acd8-48b4-bdbc-4a31034f3dd1"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-prod"
template_id = "bj6xgzx26nbp86pbdia6"
